
platform :ios, "8.0"
source 'https://github.com/CocoaPods/Specs.git'
target 'blueTooth' do
    pod 'Masonry'
    pod 'CocoaAsyncSocket'
    pod 'ReactiveObjC'
    pod 'BabyBluetooth'
    pod 'OpenSSL'
end


